name: Install and Cache Node Modules
description: Checkout repo, setup Node.js, and install dependencies with npm ci.
inputs:
  node-version:
    description: Node.js version to use
    required: true
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

